version: "3"
services:
  python:
    build:
      context: ../
      dockerfile: .devcontainer/infra/python/Dockerfile
    env_file:
      - .env
    tty: true
    volumes:
      - ../:/home/dev/data
      # WSL環境で構築しているのでちょっと変わったマウントをする。
      - type: bind
        source: ${FILE_PATH}
        target: /home/dev/data/src
      - ~/.gitconfig:/data/.gitconfig
